#!/usr/bin/env python3

#This is going to create menus and ^top links for Github pages. Hopefully.

import os


#################################################################33
#
# Steven Luther - Create GitHub Menus for long docs.
# Initial Creation: July 3 2016
#
# Changelog
#
#
#
#
	



def getUser():
	#Gets Users Github URL from .git/config
	print("--------start getUrl-----------")
	inFile = "/home/steven/scripts/gitMenu/.git/config"
	#get Config file from /.git/config
	url = ''
	print(url)
	with open (inFile, "r") as fileIn:
		for line in fileIn:
			if line[0:7] == "\turl = ":
				url = line.replace("\turl = ", "")
	return url

def getFile():
	#Gets list of needed menu items from README.md
	print("---------START getFile ---------")
	#Get the README.md file from current directory.
	list = []
	with open("README.md", "r") as fileIn:
		for line in fileIn:
			if line[0:3] == "## ":
				list += line.splitlines() 
	return list

def makeUrls():
	#Handles the list of completed URLS.
	print("--------- START makeUrls --------------")
	menuList = [getUser().replace("\n", "#")
		 + item.strip('## ').replace(' ', '-').lower() for item in getFile()]
	print(menuList)


def makeMenu():
	urls = makeUrls()
	print("-------- Start MakeMenu ----------")
	urlTags = [item.strip('## ').upper() for item in getFile()]
	print(''.join([str(a) + b for a,b in zip(urlTags, urls)]))


def main():
	makeMenu()
	makeUrls()


if __name__ == '__main__':
	main()

